name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.19'

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Setup Laravel project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate

      - name: Set permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Run PHPUnit tests
        env:
          APP_ENV: testing
        run: php artisan test

      # Add deployment steps here if necessary
